### ISSUE TITLE
Rotation/resizing handles hidden when out of the page

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2042]
## Bug Description
When resizing an image to be as large as the page or larger, the handles are not visible, disabling the option to resize / rotate the element if that handle is out of the page limits.

## Expected Behaviour
UX Needed but perhaps we should consider showing just the selection box for a selected element outside of the page as well?

## Steps to Reproduce
I
1. Add an element, e.g. Image
2. Resize it a little bit out of the limits of the page from both sides.
3. Try to resize it back smaller from the same handles.

II
1. Add an image
2. Resize it to cover most of the page
3. Now rotate it around 90 degrees
4. Try to rotate it back via the rotate handle.

## Screenshots

![rotate](https://user-images.githubusercontent.com/3294597/83042386-e562d780-a041-11ea-8d5d-7c3048bede58.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@o-fernandez Any thoughts on what might be the expected behavior here? Perhaps we should always display the selection border, even if outside of the page. Thoughts?

**Comment by o-fernandez** [comment]
> @o-fernandez Any thoughts on what might be the expected behavior here? Perhaps we should always display the selection border, even if outside of the page. Thoughts?

We also had a problem in the past of elements outside of the canvas blocking other actions (e.g., the arrows to move to next/prev page) so we'd want to avoid that... Need Sam's input before acting on this.

**Comment by samitron7** [comment]
There seems to be multiple ticket for the same issues ([#2162](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/2162)) and the one Omar mentioned which I can't find the ticket to. But they address all related things so I suggest collapsing into one.

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9517%3A0) flow for all of these issues

Removing UX Needed label

**Comment by miina** [comment]
This got already fixed in #2285 
Closing as such.

**Comment by samitron7** [comment]
@miina So there is still an issue with rotation here. When an element is rotated outside of the page such that the handles are on top of any of the page actions of the left and right nav buttons, the selection box handles should take precedence. Currently that is not the case:
 ![Screen Shot 2020-06-14 at 11.06.00 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/b38b0dc3-0d28-4761-9ff3-d6fd4a838f12)

Figma flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A1796)

Not sure where to move this so leaving in UAT.

**Comment by swissspidy** [comment]
Issues failing UAT will be labelled as such, and a new issue needs to be created for the parts that still need fixing.

**Comment by miina** [comment]
^ cc @jauyong

**Comment by o-fernandez** [comment]
Filed #2463 to capture Sam's finding. Closing this issue.
