### ISSUE TITLE
UI difficulties on small resolutions screens

### ISSUE THREAD

**Issue by budtan** [GoogleForCreators/web-stories-wp#4517]
There's no button to save or publish. After spending hours to create a story, my work just vanished because it won't save or publish.

**Comment by swissspidy** [comment]
Hi @budtan, can you please provide a screenshot of the editor? Use the GitHub website to upload it.

Also, can you provide the following information:

- Operating system
- Browser and browser version
- Site Health information (available in WP admin via Tools -> Site Health -> Info -> Copy to clipboard)

**Comment by budtan** [comment]
Hi Pascal,

Attached are the issues in addition to the missing buttons.
Operating system: Windows 10
Browser: Chrome version: 85.0.4183.102 (Official Build) (64-bit)
Site Health information:
`
### wp-core ###

version: 5.5.1
site_language: en_CA
user_language: en_CA
timezone: America/Toronto
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home3/squirrl2/public_html
wordpress_size: loading...
uploads_path: /home3/squirrl2/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home3/squirrl2/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home3/squirrl2/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (3) ###

advanced-cache.php: true
db-error.php: true
maintenance.php: true

### wp-active-theme ###

name: MH Purity (mh-purity)
version: 1.5.3
author: MH Themes
author_website: https://www.mhthemes.com/
parent_theme: none
theme_features: core-block-patterns, custom-header, title-tag,
automatic-feed-links, custom-background, post-thumbnails,
customize-selective-refresh-widgets, menus, widgets
theme_path: /home3/squirrl2/public_html/wp-content/themes/mh-purity
auto_update: Disabled

### wp-themes-inactive (1) ###

PridMag: version: 1.0.7, author: ThemezHut Themes,Auto-updates disabled

### wp-mu-plugins (4) ###

Endurance Browser Cache: version: 0.4, author: Mike Hansen
Endurance Page Cache: version: 2.0.2, author: Mike Hansen
Endurance PHP Edge: version: 0.2, author: Mike Hansen
SSO: version: 0.3, author: Garth Mortensen, Mike Hansen

### wp-plugins-active (23) ###

All In One WP Security: version: 4.4.4, author: Tips and Tricks HQ, Peter
Petreski, Ruhul, Ivy, Auto-updates disabled
CI Backlinks: version: 1.3.10, author: Creative Insight, Auto-updates
disabled
Contact Form 7: version: 5.2.2, author: Takayuki Miyoshi, Auto-updates
disabled
Contextual Related Posts: version: 2.9.3, author: WebberZone, Auto-updates
disabled
Google Analytics for WordPress by MonsterInsights: version: 7.12.2, author:
MonsterInsights, Auto-updates enabled
Grow by Mediavine: version: 1.7.0, author: Mediavine, Auto-updates disabled
Menu Image: version: 2.9.7, author: Rui Guerreiro, Auto-updates disabled
Newsletter: version: 6.8.8, author: Stefano Lissa & The Newsletter Team,
Auto-updates disabled
Newsletter - Addons Manager: version: 1.1.3, author: The Newsletter Team,
Auto-updates disabled
Newsletter - Archive: version: 4.0.3, author: The Newsletter Team,
Auto-updates disabled
Newsletter - Instasend (BETA): version: 1.0.2, author: The Newsletter Team,
Auto-updates disabled
Newsletter - Sendinblue: version: 1.0.0, author: The Newsletter Team,
Auto-updates disabled
Pretty Links: version: 3.1.1, author: Pretty Links, Auto-updates disabled
Reading Time WP: version: 2.0.10, author: Jason Yingling, Auto-updates
disabled
Regenerate Thumbnails: version: 3.1.3, author: Alex Mills (Viper007Bond),
Auto-updates disabled
Social Media and Share Icons (Ultimate Social Media): version: 2.5.9,
author: UltimatelySocial, Auto-updates disabled
Social Media Flying Icons | Floating Social Media Icon: version: 4.3.4,
author: Acurax, Auto-updates disabled
Stop Spammers: version: 2020.5, author: Trumani, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.16.29, author: UpdraftPlus.Com,
DavidAnderson, Auto-updates disabled
W3 Total Cache: version: 0.14.4, author: BoldGrid, Auto-updates disabled
Web Stories: version: 1.0.0-rc.1, author: Google, Auto-updates disabled
Wp-Insert: version: 2.4.8, author: Namith Jawahar, Auto-updates disabled
Yoast SEO: version: 14.9, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (1) ###

Internal Link Juicer: version: 1.2.6, author: Internal Link Juicer,
Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01
https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 260M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits:
imagick::RESOURCETYPE_AREA: 115 GB
imagick::RESOURCETYPE_DISK: 9223372036854775807
imagick::RESOURCETYPE_FILE: 12288
imagick::RESOURCETYPE_MAP: 48 MB
imagick::RESOURCETYPE_MEMORY: 48 MB
imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 4.14.94-164.ELK.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.0.33 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 260M
curl_version: 7.72.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.23-23
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id:
b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home3/squirrl2/public_html/wp-content
WP_PLUGIN_DIR: /home3/squirrl2/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

Thanks,
Bryan

**Comment by ernee** [comment]
@budtan thanks for the info! Unfortunately, we cannot view image attachments from email. Could you upload your screenshots directly to the issue on Github?

**Comment by budtan** [comment]
[Web Stories Issues.pptx](https://github.com/google/web-stories-wp/files/5243078/Web.Stories.Issues.pptx)

**Comment by swissspidy** [comment]
Thanks!

Re-adding here for better visibility:

<img width="907" alt="Screenshot 2020-09-18 at 10 47 49" src="https://user-images.githubusercontent.com/841956/93577522-761c4500-f99c-11ea-8c43-5e63b3bc412e.png">

<img width="905" alt="Screenshot 2020-09-18 at 10 47 55" src="https://user-images.githubusercontent.com/841956/93577507-7288be00-f99c-11ea-8280-3a52e3d852d8.png">


@budtan The editor looks a bit small. What's your computer's screen size? Please note that the editor does not currently support smaller screen sizes very well.

I suggest trying it on a desktop computer to see if it works better there.

Also, thanks for raising the issue with the scrollbar color. It's something we'll pass along to the team.

**Comment by budtan** [comment]
My laptop is 11’

**Comment by ernee** [comment]
@budtan thanks for the info! Just a quick check: do you still experience this with the stable version of the plugin 1.0.0?

**Comment by budtan** [comment]
Hi Renee,

Unfortunately, it still happens. Only sometimes the buttons would show up,
especially after publishing the story.
Luckily, there's a Ctrl+S shortcut now so I can save it, and select the
publish date and time.

**Comment by ernee** [comment]
@budtan many thanks for providing this update!

**Comment by dreamofabear** [comment]
@budtan Thanks for the detailed info. What's your screen resolution?

**Comment by budtan** [comment]
1366 x 768

**Comment by o-fernandez** [comment]
@budtan thanks again for all the info. 

@carlos-kelly @barklund for evaluation if this can fit into this sprint. Note that 1366x768 is the second most popular screen resolution we see, so it would be great to check our responsiveness and ensure things work smoothly in that resolution. Also @samitron7 for any UX thoughts on this.

**Comment by swissspidy** [comment]
This resolution works fine in my testing, but it seems like there are issues when lots of plugins are active, making the admin menu excessively long:

<img width="1432" alt="Screen Shot 2020-10-05 at 11 02 54 AM" src="https://user-images.githubusercontent.com/841956/95097995-6b003d80-072e-11eb-88e3-5449dd872f2a.png">

Maybe it's a similar issue here, as https://github.com/google/web-stories-wp/issues/4517#issuecomment-693787321 lists 23 active plugins

**Comment by samitron7** [comment]
We have treatment for smaller screen in the new visual pass that will address the scrollbar and other minor layout issues. The other issues described seems to be bugs as Pascal pointed out.

**Comment by swissspidy** [comment]
Created #5076 for the issue I mentioned above.

Also created #5077 specifically for addressing https://github.com/google/web-stories-wp/issues/4517#issuecomment-694743971 as it has came up a few times and can be fixed independently from the visual pass or other layout issues.

**Comment by BrittanyIRL** [comment]
(We should take a look at this next sprint and see if issues are resolved with redesign)

**Comment by BrittanyIRL** [comment]
Lost track of this, I think it's fixed with our design updates earlier this year. @budtan are you still having issues with the save button?

**Comment by bmattb** [comment]
@swissspidy & @gajasinski - This is flagged as a roadmap item for v1.15.0, can we get confirmation that this is still a valid issue and has not been previously addressed by redesign efforts?

**Comment by gajasinski** [comment]
@swissspidy can you help confirm?

**Comment by dreamofabear** [comment]
This is still an issue and I believe @agingoldseco has already started looking into it.

**Comment by bmattb** [comment]
@agingoldseco Please let us know when you have something for review as we will likely need to book a review session with you & @gajasinski to review together and ask all the questions :)

**Comment by agingoldseco** [comment]
@bmattb @gajasinski @choumx  - Sure! Could have this meeting as soon as Thursday to show my preliminary ideas and get some feedback :)
