### ISSUE TITLE
Design panel missing video poster image field when video set as background

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6075]
## Bug Description
When you set a video as a background on a page the poster image field in the design panel no longer displays.

## Expected Behaviour

There should be a poster image field when you set a video as a background.

## Steps to Reproduce

1. Drag video on to canvas and poster field displays ([screenshot](https://jumpshare.com/v/SZuw3wPhlKWZY1zlPsUO)).
2. Set video as background and poster field removed ([screenshot](https://jmp.sh/vJIvrFk)).

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: MacBook Pro (13-inch)
- Browser: Chrome v. 88.0.4324.96

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @barklund for prioritization

should be an easy fix

**Comment by miina** [comment]
FYI: Probably related: when a custom poster is previously set then setting the video as background (and detaching again) resets the poster to the original.

**Comment by swissspidy** [comment]
> FYI: Probably related: when a custom poster is previously set then setting the video as background (and detaching again) resets the poster to the original.

That doesn't sound good :-( Definitely need to fix that too.

**Comment by barklund** [comment]
Fixed by other work.

**Comment by swissspidy** [comment]
@barklund @miina Still seeing the issue Miina mentioned about the custom poster being deleted. Could you create a new ticket for that?

**Comment by miina** [comment]
Added: https://github.com/google/web-stories-wp/issues/6963
